name: Build SunamoHtml

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    name: Build SunamoHtml
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore SunamoHtml/SunamoHtml.csproj

    - name: Build
      run: dotnet build SunamoHtml/SunamoHtml.csproj --configuration Release --no-restore

  test:
    name: Test SunamoHtml.Tests
    runs-on: ${{ matrix.os }}
    needs: build

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore SunamoHtml.Tests/SunamoHtml.Tests.csproj

    - name: Build tests
      run: dotnet build SunamoHtml.Tests/SunamoHtml.Tests.csproj --configuration Release --no-restore

    - name: Run tests
      run: dotnet test SunamoHtml.Tests/SunamoHtml.Tests.csproj --configuration Release --no-build --verbosity normal
      continue-on-error: true
